### ISSUE TITLE
Support for private repositories with always-auth

### ISSUE THREAD

**Issue by SystemParadox** [dylang/npm-check#11]
Hi.

I would love to use npm-check but at the moment I can't convince it to use my ~/.npmrc settings. Specifically, we use an internal private npm registry (sinopa), which requires always-auth.

Is there any chance this could be supported somehow?

Thanks very much.

**Comment by dylang** [comment]
Interesting. We have an internal `npm` server, but we don't have that problem. I'll see if I can set up [sinopa](https://www.npmjs.com/package/sinopia) and have the same problem. 

Besides this problem, how has using Sinopia been?

**Comment by dylang** [comment]
I set up `sinopa` and turned on `always-auth` and `npm-check` seems to be working fine.

`npm-check` *only* uses your `~/.npmrc` via [npmconf](https://www.npmjs.com/package/npmconf), it's not hardcoded to any particlar registry, and it uses `npm`'s code for making the api calls, so it should support anything `npm` can do. You can see that code in [lib/npm/get-conf.js](https://github.com/dylang/npm-check/blob/master/lib/npm/get-conf.js).

What kind of errors are you seeing?

**Comment by SystemParadox** [comment]
Sinopia is great. Really easy to setup, works very well for us.

When running npm-check it outputs the following for all private packages:

```
[registry url] returned can't access restricted package without auth, did you forget 'npm set always-auth true'?
```

**Comment by SystemParadox** [comment]
Playing around with the code in get-conf it appears that the registryClient just uses the npmConfig shim object with the custom logger. It's not actually reading the npm config from anywhere.

In addition, looking at the documentation for `npm-registry-client` it seems that `client.get` takes authentication credentials. I'm not sure if that's just an override or if this means it will not fall back to reading them from the config.

**Comment by dylang** [comment]
Ahh - because your server has this set:

```
allow_access: $authenticated
```

I didn't think about that, I was thinking auth would only be used for publishing which `npm-check`  doesn't do. Good detective work with regards to `get-conf` and `npm-registry-client`, do you have a workaround in mind? Do you want to make a pull request?

**Comment by tndev** [comment]
Not sure if it is a problem in my configuration, but the patched version of SystemParadox itself works fine for me, but the updated version `4.0.1` results in a `Registry error GET .... response code is 403 (Forbidden)` error for all modules.

**Comment by tndev** [comment]
I looked closer in the code and recognised, that this particular functionality is now handled by the `package-json` module that seems not to support authentication. So am i right that private password protected repositories are still not supported or am I missing something?

**Comment by dylang** [comment]
@tndev Thanks for investigating that. Can you report this issue with [package-json](https://github.com/sindresorhus/package-json)?

**Comment by nopnop** [comment]
Maybe related (or at least, nice to reference here): If your private npm server (sinopia, or any) use a self signed certificat, package-json wont work either. 
We can bypass the ssl checking (!) with `NODE_TLS_REJECT_UNAUTHORIZED` env var:
```
NODE_TLS_REJECT_UNAUTHORIZED=0 npm-check
```
By the way, this is not really an issue for `npm-check` nor `package-json`. See this related  [stackoverflow thread](http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature).

**Comment by jameswomack** [comment]
Hey, thank you for this very useful tool. 🌟 

I'm still experiencing the issue that @tndev mentioned. In my case, it's an Artifactory registry over at Netflix.The System Paradox fork works, npm-check does not. `NODE_TLS_REJECT_UNAUTHORIZED=0` has no effect. 

I've looked at https://github.com/sindresorhus/package-json/issues/18, but `always-auth=true` isn't used there either, and setting it to false.

**Comment by madx** [comment]
It seems like the issue has been fixed in https://github.com/sindresorhus/package-json/commit/c904e9e3353886224439178ae095ef600ff99620
Maybe it's only a matter of upgrading the dependencies then?

**Comment by SystemParadox** [comment]
It appears that this is still not working in the latest version (5.4.0). I tried manually updating package-json to 4.0.0, but that didn't help.

I just get lots of `Registry error Response code 403 (Forbidden)` errors :(

**Comment by jameswomack** [comment]
@SystemParadox true. I still need to use your old fork if I want this to work.

**Comment by SystemParadox** [comment]
There is now a builtin `npm outdated` command, which does much of what npm-check does.

It is definitely more limited than npm-check though - it doesn't check for unused dependencies, for example.

**Comment by jameswomack** [comment]
Yes—unused deps were my main use case. They drive me nuts 🥜

**Comment by Ilhicas** [comment]
NODE_TLS_REJECT_UNAUTHORIZED=0 actually works for self-signed issues where you always get
                                    ⛔  NPM ERR!  Registry error unable to verify the first certificate
And not making use of any configuration via npm-config setting a Certificate Authority.
